/*
 * This file is generated by jOOQ.
*/
package de.quinscape.domainqlstarter.domain;


import de.quinscape.domainqlstarter.domain.tables.AppLogin;
import de.quinscape.domainqlstarter.domain.tables.AppUser;
import de.quinscape.domainqlstarter.domain.tables.Foo;
import de.quinscape.domainqlstarter.domain.tables.FooType;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.app_login</code>.
     */
    public static final AppLogin APP_LOGIN = de.quinscape.domainqlstarter.domain.tables.AppLogin.APP_LOGIN;

    /**
     * The table <code>public.app_user</code>.
     */
    public static final AppUser APP_USER = de.quinscape.domainqlstarter.domain.tables.AppUser.APP_USER;

    /**
     * The table <code>public.foo</code>.
     */
    public static final Foo FOO = de.quinscape.domainqlstarter.domain.tables.Foo.FOO;

    /**
     * The table <code>public.foo_type</code>.
     */
    public static final FooType FOO_TYPE = de.quinscape.domainqlstarter.domain.tables.FooType.FOO_TYPE;
}
